#!/bin/sh
./gameboy BROKER APPEARED_POKEMON Onix 2 8 0
./gameboy BROKER APPEARED_POKEMON Gengar 6 6 0
./gameboy BROKER APPEARED_POKEMON Squirtle 5 5 0

./gameboy BROKER APPEARED_POKEMON Umbreon 10 6 0
./gameboy BROKER APPEARED_POKEMON Espeon 7 1 0
./gameboy BROKER APPEARED_POKEMON Vaporeon 4 10 0
